<!doctype html>
<html lang="en"><head><meta charSet="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Mochawesome Report</title><link rel="stylesheet" href="assets/app.css"/></head><body data-raw="{&quot;stats&quot;:{&quot;suites&quot;:2,&quot;tests&quot;:6,&quot;passes&quot;:1,&quot;pending&quot;:0,&quot;failures&quot;:5,&quot;start&quot;:&quot;2020-05-22T22:57:13.927Z&quot;,&quot;end&quot;:&quot;2020-05-22T22:57:13.927Z&quot;,&quot;duration&quot;:12766,&quot;testsRegistered&quot;:6,&quot;passPercent&quot;:16.666666666666668,&quot;pendingPercent&quot;:0,&quot;other&quot;:0,&quot;hasOther&quot;:false,&quot;skipped&quot;:0,&quot;hasSkipped&quot;:false},&quot;results&quot;:[{&quot;uuid&quot;:&quot;118953bb-250c-428a-adc3-0aaa52bfea74&quot;,&quot;title&quot;:&quot;&quot;,&quot;fullFile&quot;:&quot;cypress/integration/test-spec.js&quot;,&quot;file&quot;:&quot;cypress/integration/test-spec.js&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[],&quot;suites&quot;:[{&quot;uuid&quot;:&quot;aebbf2cc-9c24-4c98-bdc8-85def0fb2533&quot;,&quot;title&quot;:&quot;home&quot;,&quot;fullFile&quot;:&quot;&quot;,&quot;file&quot;:&quot;&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[{&quot;title&quot;:&quot;can visit homepage&quot;,&quot;fullTitle&quot;:&quot;home can visit homepage&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:1276,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:&quot;slow&quot;,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;cy.visit(&#x27;/&#x27;);&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/__coverage__\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://localhost:8080/__coverage__\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n    at new RequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n    at ClientRequest.emit (events.js:215:7)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n\n\nhttps://on.cypress.io/request\n\nBecause this error occurred during a `after all` hook we are skipping all of the remaining tests.&quot;,&quot;estack&quot;:&quot;CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/__coverage__\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://localhost:8080/__coverage__\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n    at new RequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n    at ClientRequest.emit (events.js:215:7)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n\n\nhttps://on.cypress.io/request\n\nBecause this error occurred during a `after all` hook we are skipping all of the remaining tests.\n&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;7b9b836a-d959-49fc-ac7f-4b19d770afea&quot;,&quot;parentUUID&quot;:&quot;aebbf2cc-9c24-4c98-bdc8-85def0fb2533&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false}],&quot;suites&quot;:[],&quot;passes&quot;:[],&quot;failures&quot;:[&quot;7b9b836a-d959-49fc-ac7f-4b19d770afea&quot;],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:1276,&quot;root&quot;:false,&quot;rootEmpty&quot;:false,&quot;_timeout&quot;:2000},{&quot;uuid&quot;:&quot;ca4eab6e-dcb7-4626-b247-0d88437fd440&quot;,&quot;title&quot;:&quot;Users&quot;,&quot;fullFile&quot;:&quot;&quot;,&quot;file&quot;:&quot;&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[{&quot;title&quot;:&quot;Can create user&quot;,&quot;fullTitle&quot;:&quot;Users Can create user&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:907,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:null,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;cy.request(&#x27;POST&#x27;, \&quot;\&quot;.concat(Cypress.config(&#x27;apiUrl&#x27;), \&quot;/auth/user\&quot;), {\n  firstName: &#x27;charles&#x27;,\n  lastName: &#x27;brady&#x27;,\n  email: &#x27;ranom&#x27;,\n  password: &#x27;myPassword1!&#x27;\n}).then(function (response) {\n  // response.body is automatically serialized into JSON\n  expect(response.body).to.have.property(&#x27;firstName&#x27;, &#x27;charles&#x27;); // true\n});&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/auth/user\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: http://localhost:8080/auth/user\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n    at new RequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n    at ClientRequest.emit (events.js:215:7)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n\n\nhttps://on.cypress.io/request&quot;,&quot;estack&quot;:&quot;CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/auth/user\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: http://localhost:8080/auth/user\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n    at new RequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n    at ClientRequest.emit (events.js:215:7)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n\n\nhttps://on.cypress.io/request\n&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;d7f14833-82e1-4b90-a80d-16ff02ec76de&quot;,&quot;parentUUID&quot;:&quot;ca4eab6e-dcb7-4626-b247-0d88437fd440&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false},{&quot;title&quot;:&quot;Can authenticate user&quot;,&quot;fullTitle&quot;:&quot;Users Can authenticate user&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:924,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:null,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;cy.request(&#x27;POST&#x27;, \&quot;\&quot;.concat(Cypress.config(&#x27;apiUrl&#x27;), \&quot;/auth/authenticate\&quot;), {\n  email: &#x27;ranom&#x27;,\n  password: &#x27;myPassword1!&#x27;\n}).then(function (response) {\n  expect(response.body).to.equal(&#x27;OK&#x27;);\n});&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/auth/authenticate\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: http://localhost:8080/auth/authenticate\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n    at new RequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n    at ClientRequest.emit (events.js:215:7)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n\n\nhttps://on.cypress.io/request&quot;,&quot;estack&quot;:&quot;CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/auth/authenticate\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: POST\nURL: http://localhost:8080/auth/authenticate\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n    at new RequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n    at ClientRequest.emit (events.js:215:7)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n\n\nhttps://on.cypress.io/request\n&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;52fcfae9-84e3-46f8-bc6d-c4d03430eb90&quot;,&quot;parentUUID&quot;:&quot;ca4eab6e-dcb7-4626-b247-0d88437fd440&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false}],&quot;suites&quot;:[],&quot;passes&quot;:[],&quot;failures&quot;:[&quot;d7f14833-82e1-4b90-a80d-16ff02ec76de&quot;,&quot;52fcfae9-84e3-46f8-bc6d-c4d03430eb90&quot;],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:1831,&quot;root&quot;:false,&quot;rootEmpty&quot;:false,&quot;_timeout&quot;:2000}],&quot;passes&quot;:[],&quot;failures&quot;:[],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:0,&quot;root&quot;:true,&quot;rootEmpty&quot;:true,&quot;_timeout&quot;:2000},{&quot;uuid&quot;:&quot;e67a515c-66af-471d-893e-0554ccc56f74&quot;,&quot;title&quot;:&quot;&quot;,&quot;fullFile&quot;:&quot;cypress/integration/test.js&quot;,&quot;file&quot;:&quot;cypress/integration/test.js&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[],&quot;suites&quot;:[{&quot;uuid&quot;:&quot;f0bf0127-bbae-43fe-adaf-fa4c9a30c712&quot;,&quot;title&quot;:&quot;Users&quot;,&quot;fullFile&quot;:&quot;&quot;,&quot;file&quot;:&quot;&quot;,&quot;beforeHooks&quot;:[],&quot;afterHooks&quot;:[],&quot;tests&quot;:[{&quot;title&quot;:&quot;Can create user&quot;,&quot;fullTitle&quot;:&quot;Users Can create user&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:2757,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:&quot;slow&quot;,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;cy.visit(&#x27;/&#x27;);\ncy.get(&#x27;[data-test=\&quot;register-navlink\&quot;]&#x27;).click();\ncy.get(&#x27;[data-test=\&quot;firstName-input\&quot;]&#x27;).type(&#x27;Charles&#x27;);\ncy.get(&#x27;[data-test=\&quot;lastName-input\&quot;]&#x27;).type(&#x27;Charles&#x27;);\ncy.get(&#x27;[data-test=\&quot;email-input\&quot;]&#x27;).type(&#x27;charlesmbrady@gmail.com&#x27;);\ncy.get(&#x27;[data-test=\&quot;password-input\&quot;]&#x27;).type(&#x27;Password1!&#x27;);\ncy.get(&#x27;[data-test=\&quot;passwordConfirmation-input\&quot;]&#x27;).type(&#x27;Password1!&#x27;);\ncy.get(&#x27;[data-test=\&quot;submit-button\&quot;]&#x27;).click();&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/__coverage__\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://localhost:8080/__coverage__\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n    at new RequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n    at ClientRequest.emit (events.js:215:7)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n\n\nhttps://on.cypress.io/request\n\nBecause this error occurred during a `after all` hook we are skipping all of the remaining tests.&quot;,&quot;estack&quot;:&quot;CypressError: `cy.request()` failed trying to load:\n\nhttp://localhost:8080/__coverage__\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  &gt; Error: connect ECONNREFUSED 127.0.0.1:8080\n\n-----------------------------------------------------------\n\nThe request we sent was:\n\nMethod: GET\nURL: http://localhost:8080/__coverage__\n\n-----------------------------------------------------------\n\nCommon situations why this would fail:\n  - you don&#x27;t have internet access\n  - you forgot to run / boot your web server\n  - your web server isn&#x27;t accessible\n  - you have weird network configuration settings on your computer\n\nThe stack trace for this error is:\n\nRequestError: Error: connect ECONNREFUSED 127.0.0.1:8080\n    at new RequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:185:22)\n    at Request.emit (events.js:210:5)\n    at Request.onRequestError (/Users/charlesbrady/Library/Caches/Cypress/4.5.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/request/request.js:877:8)\n    at ClientRequest.emit (events.js:215:7)\n    at Socket.socketErrorListener (_http_client.js:406:9)\n    at Socket.emit (events.js:210:5)\n    at emitErrorNT (internal/streams/destroy.js:92:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)\n\n\nhttps://on.cypress.io/request\n\nBecause this error occurred during a `after all` hook we are skipping all of the remaining tests.\n&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;45095d51-0be8-40bc-afdc-91820eac2d43&quot;,&quot;parentUUID&quot;:&quot;f0bf0127-bbae-43fe-adaf-fa4c9a30c712&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false},{&quot;title&quot;:&quot;Can login with existing user&quot;,&quot;fullTitle&quot;:&quot;Users Can login with existing user&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:1318,&quot;state&quot;:&quot;passed&quot;,&quot;speed&quot;:&quot;slow&quot;,&quot;pass&quot;:true,&quot;fail&quot;:false,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;cy.visit(&#x27;/&#x27;);\ncy.get(&#x27;[data-test=\&quot;login-navlink\&quot;]&#x27;).click();\ncy.get(&#x27;[data-test=\&quot;email-input\&quot;]&#x27;).type(&#x27;charlesmbrady@gmail.com&#x27;);\ncy.get(&#x27;[data-test=\&quot;password-input\&quot;]&#x27;).type(&#x27;Password1!&#x27;);\ncy.get(&#x27;[data-test=\&quot;submit-button\&quot;]&#x27;).click();\ncy.visit(&#x27;/dashboard&#x27;);&quot;,&quot;err&quot;:{},&quot;uuid&quot;:&quot;59ea8c1c-2bbe-49d7-8e43-b8e336791368&quot;,&quot;parentUUID&quot;:&quot;f0bf0127-bbae-43fe-adaf-fa4c9a30c712&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false},{&quot;title&quot;:&quot;Can logout&quot;,&quot;fullTitle&quot;:&quot;Users Can logout&quot;,&quot;timedOut&quot;:null,&quot;duration&quot;:5584,&quot;state&quot;:&quot;failed&quot;,&quot;speed&quot;:null,&quot;pass&quot;:false,&quot;fail&quot;:true,&quot;pending&quot;:false,&quot;context&quot;:null,&quot;code&quot;:&quot;cy.visit(&#x27;/&#x27;);\ncy.get(&#x27;[data-test=\&quot;login-navlink\&quot;]&#x27;).click();\ncy.get(&#x27;[data-test=\&quot;email-input\&quot;]&#x27;).type(&#x27;charlesmbrady@gmail.com&#x27;);\ncy.get(&#x27;[data-test=\&quot;password-input\&quot;]&#x27;).type(&#x27;Password1!&#x27;);\ncy.get(&#x27;[data-test=\&quot;submit-button\&quot;]&#x27;).click();\ncy.visit(&#x27;/dashboard&#x27;);\ncy.get(&#x27;[data-test=\&quot;logout-button\&quot;]&#x27;).click();&quot;,&quot;err&quot;:{&quot;message&quot;:&quot;AssertionError: Timed out retrying: Expected to find element: `[data-test=\&quot;logout-button\&quot;]`, but never found it.&quot;,&quot;estack&quot;:&quot;AssertionError: Timed out retrying: Expected to find element: `[data-test=\&quot;logout-button\&quot;]`, but never found it.\n    at ensureExistence (http://localhost:8081/__cypress/runner/cypress_runner.js:137673:32)\n    at Object.ensureElExistence (http://localhost:8081/__cypress/runner/cypress_runner.js:137691:12)\n    at ensureExistence (http://localhost:8081/__cypress/runner/cypress_runner.js:127867:23)\n    at onFailFn (http://localhost:8081/__cypress/runner/cypress_runner.js:127905:9)\n    at tryCatcher (http://localhost:8081/__cypress/runner/cypress_runner.js:9065:23)\n    at Promise._settlePromiseFromHandler (http://localhost:8081/__cypress/runner/cypress_runner.js:7000:31)\n    at Promise._settlePromise (http://localhost:8081/__cypress/runner/cypress_runner.js:7057:18)\n    at Promise._settlePromise0 (http://localhost:8081/__cypress/runner/cypress_runner.js:7102:10)\n    at Promise._settlePromises (http://localhost:8081/__cypress/runner/cypress_runner.js:7178:18)\n    at _drainQueueStep (http://localhost:8081/__cypress/runner/cypress_runner.js:3772:12)\n    at _drainQueue (http://localhost:8081/__cypress/runner/cypress_runner.js:3765:9)\n    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8081/__cypress/runner/cypress_runner.js:3781:5)\n    at Async.drainQueues (http://localhost:8081/__cypress/runner/cypress_runner.js:3651:14)&quot;,&quot;diff&quot;:null},&quot;uuid&quot;:&quot;e0bdd07e-8731-46da-90bd-ecb8fff254b6&quot;,&quot;parentUUID&quot;:&quot;f0bf0127-bbae-43fe-adaf-fa4c9a30c712&quot;,&quot;isHook&quot;:false,&quot;skipped&quot;:false}],&quot;suites&quot;:[],&quot;passes&quot;:[&quot;59ea8c1c-2bbe-49d7-8e43-b8e336791368&quot;],&quot;failures&quot;:[&quot;45095d51-0be8-40bc-afdc-91820eac2d43&quot;,&quot;e0bdd07e-8731-46da-90bd-ecb8fff254b6&quot;],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:9659,&quot;root&quot;:false,&quot;rootEmpty&quot;:false,&quot;_timeout&quot;:2000}],&quot;passes&quot;:[],&quot;failures&quot;:[],&quot;pending&quot;:[],&quot;skipped&quot;:[],&quot;duration&quot;:0,&quot;root&quot;:true,&quot;rootEmpty&quot;:true,&quot;_timeout&quot;:2000}],&quot;meta&quot;:{&quot;mocha&quot;:{&quot;version&quot;:&quot;7.0.1&quot;},&quot;mochawesome&quot;:{&quot;options&quot;:{&quot;quiet&quot;:true,&quot;reportFilename&quot;:&quot;mochawesome&quot;,&quot;saveHtml&quot;:false,&quot;saveJson&quot;:true,&quot;consoleReporter&quot;:&quot;spec&quot;,&quot;useInlineDiffs&quot;:false},&quot;version&quot;:&quot;4.1.0&quot;},&quot;marge&quot;:{&quot;options&quot;:{&quot;reportDir&quot;:&quot;cypress/reports/integration/reports/mocha&quot;,&quot;quiet&quot;:true,&quot;html&quot;:false,&quot;overwrite&quot;:false,&quot;json&quot;:true},&quot;version&quot;:&quot;4.1.0&quot;}}}" data-config="{&quot;reportFilename&quot;:&quot;report&quot;,&quot;reportDir&quot;:&quot;cypress/reports/integration/public/&quot;,&quot;reportTitle&quot;:&quot;MERNolithic_sql&quot;,&quot;reportPageTitle&quot;:&quot;Mochawesome Report&quot;,&quot;inline&quot;:false,&quot;inlineAssets&quot;:false,&quot;cdn&quot;:false,&quot;charts&quot;:false,&quot;enableCharts&quot;:false,&quot;code&quot;:true,&quot;enableCode&quot;:true,&quot;autoOpen&quot;:false,&quot;overwrite&quot;:true,&quot;timestamp&quot;:false,&quot;ts&quot;:false,&quot;showPassed&quot;:true,&quot;showFailed&quot;:true,&quot;showPending&quot;:true,&quot;showSkipped&quot;:false,&quot;showHooks&quot;:&quot;failed&quot;,&quot;saveJson&quot;:false,&quot;saveHtml&quot;:true,&quot;dev&quot;:false,&quot;assetsDir&quot;:&quot;cypress/reports/integration/public/assets&quot;,&quot;htmlFile&quot;:&quot;/Users/charlesbrady/Desktop/cleanup/Development/Starters/MERNolithic_sql/cypress/reports/integration/public/report.html&quot;}"><div id="report"></div><script src="assets/app.js"></script></body></html>